name: FancyGenerators
main: surva\fancygenerators\FancyGenerators
version: 1.2.2
api: 5.0.0

author: survanetwork
description: A collection of new level Generators
website: https://dev.surva.net/plugins/#fancygenerators
